---
# 3tier playbook
- hosts: all
      
  roles:
    - { role: tomcat, when: "'groupname' == 'apps'", tags: "tomcat,apps" }
    - { role: httpd, when: "'groupname' == 'apps'", tags: "httpd,apps" }
    - { role: haproxy, when: "'groupname' == 'frontend'", tags: "haproxy,frontend" }
    - { role: postgres, when: "'groupname' == 'db'", tags: "postgres,db" }
  
