---
  #create networks
- hosts: jumpbox
  vars_files: 
    - ./vars/network_vars.yml
 
  tasks:
    - name: create networks
      os_network:
        name: "{{ item.key }}"
        cloud: "{{ cloud }}"
        external: "{{ item.value.external }}"
        state: present
      with_dict: "{{ networks }}"
 
    - name: test
      debug: 
        msg: "dns 1 value is {{ item.value.dns.dns1 }} and key is {{ item.key }}"
      with_dict: "{{ networks }}"

    - name: create subnets
      os_subnet:
        state: present
        cloud: "{{ cloud }}"
        network_name: "{{ item.key }}"
        name: "{{ item.key}}_subnet"
        cidr: "{{ item.value.cidr }}"
        dns_nameservers: 
          - "{{ item.value.dns.dns1 }}"
          - "{{ item.value.dns.dns2 }}"
        host_routes:
          - destination: "{{ item.value.route.dest }}"
            nexthop: "{{ item.value.route.next }}"
      with_dict: "{{ networks }}"



