---
#Setup playbook for Openstack jumphost
- hosts: workstation

  tasks:
    - name: copy open.repo to jumphost
      copy:
        remote_src: "ctrl-{{ GUID }}.rhpds.opentlc.com:/etc/yum.repos.d/open.repo"
        dest: /etc/yum.repos.d/open.repo
    
    - name: install "{{ item }}" python-openstackclient
      yum:
        name: "{{ item }}"
        state: latest
      with_items: 
        - python-openstackclient

    - name: copy keystonerc_admin to /root/
      copy:
        remote_src: ctrl.example.com:/root/keystonerc_admin
        dest: /root/
      become: true

    - name: copy openstack.pub to jumphost
      get-url:
        url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        dest: ~/temp/
        
    - name: add opentstack.pub to authorized_keys
      athorized_key: 
        key: ~/temp/openstack.pub
        user: trentm-datacom.co.nz
      become: true