---
# tasks file for provision_instances
################################################################
#vars check
- name: check vars are not empty
  assert:
    that: 
      - "{{ os_keypair != '' }}"
      - "{{ os_cloud != '' }}"
      - "{{ os_image != '' }}"
################################################################

- name: provision common os_servers
  os_server:
    flavor: "{{ item.flavor }}"
    key_name: "{{ item.keypair }}"
    meta: "{{ item.metadata }}"
    nics: 
      - net-id: "{{ network_ids[0].net_id }}"
      - net-id: "{{ network_ids[1].net_id }}"
    image: "{{ item.image }}"
    name: "{{ item.name }}"
    security_group: "{{ item.sg }}"
  with_items: "{{ cloud_infra_vars_os_servers }}"
  register: result

- name: create floating ip
  os_floating_ip:
    cloud: "{{ os_cloud }}"
    nat_destination: "{{ ['private']|map('extract', { network_id })|list }}"
    network: "{{ ['public']|map('extract', { network_id })|list }}"
    state: present  

- name: test 22 access
  wait_for:
    port: 22
    timeout: 300
    host: "{{ item.server.public_v4 }}"
    search_regex: "OpenSSH"
  with_items: "{{ result.results }}"
  tags:
    - ssh_access