---
# 3tier playbook
- name: configure 3tier site
  hosts: all
  
- import_playbook: common.yml 
- import_playbook: frontends.yml
- import_playbook: apps.yml
  tags: app
- import_playbook: appdbs.yml
