---
#common configurrations
- name: common config for all servers
  hosts: all
  become: true

  tasks:
   - name: enable repos
     copy:
      src: ./files/open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

...