---
#setting up the environment
- hosts: bastion
  name: fetch pem key from bastion
  become: true

  tasks:
    - name: fetch pem key
      fetch:
        src: "/root/.ssh/{{ GUID }}key.pem"
        dest: ./temp

...