---
# tasks file for os_image_copy
- name: download RHEL image
  get_url:
    url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
    dest: /root/rhel-guest-image-7.2-20151102.0.x86_64.qcow2

- name: Upload os_image 
  os_image:
    cloud: ospcloud
    name: rhel-guest
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /root/rhel-guest-image-7.2-20151102.0.x86_64.qcow2